# Generated by Django 6.0.2 on 2026-02-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.task'),
        ),
    ]
