# Generated by Django 6.0.2 on 2026-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0007_subtask_description_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
