# Generated by Django 6.0.2 on 2026-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_remove_task_user_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Main_quest'), (2, 'Routine'), (3, 'Daily'), (4, 'Grind')], default=2),
        ),
    ]
